

(setq coq-symbols-list '(lambda ()
        (mapc (lambda (pair) (push pair prettify-symbols-alist))
            '(("forall". ?∀)
              ("exists". ?∃)
              ("~" . ?¬)
              ("/\\" . ?⋀)
              ("\\/" . ?⋁)
              ("=>". ?⇒)
              ("->". ?→)
              ("<-" . ?←)
              ("<->" . ?↔)
              ("nat" . ?ℕ)
              ("*" . ?×)
	      ("nil" . ?∅)
	      ("bot" . ?⊥)
	      ("top" . ?⊤)
	      ("decl" . ?σ)
	      ("ty" . ?τ)
	      ("env" . ?Γ)
	      ("Sig" . ?∑)
	      ("en" . ?,)
	      ("vdash" . ?⊢)
	      ("dashv" . ?⊣)
	      ("equiv" . ?≡)
	      ("equiv_d" . ?≡)
	      ("equiv_p" . ?≡)
	      ("equiv_e" . ?≡)
	      ("hasType" . ?:)
	      ("pathType" . ?:)
	      ("swap" . ?↔)
	      ("swap_t" . ?↔)
	      ("swap_d" . ?↔)
	      ("swap_p" . ?↔)
	      ("swap_e" . ?↔)
	      ("swap_n" . ?↔)
	      ("rshift_v" . ?⇁)
	      ("rshift_t" . ?⇁)
	      ("rshift_dt" . ?⇁)
	      ("rshift_dts" . ?⇁)
	      ("rshift_p" . ?⇁)
	      ("rshift_e" . ?⇁)
	      ("rshift_d" . ?⇁)
	      ("rshift_ds" . ?⇁)
	      ("lshift_v" . ?↽)
	      ("lshift_t" . ?↽)
	      ("lshift_dt" . ?↽)
	      ("lshift_dts" . ?↽)
	      ("lshift_p" . ?↽)
	      ("lshift_e" . ?↽)
	      ("lshift_d" . ?↽)
	      ("lshift_ds" . ?↽)
	      ("ljump_n" . ?↶)
	      ("ljump_v" . ?↶)
	      ("ljump_t" . ?↶)
	      ("ljump_d" . ?↶)
	      ("ljump_ds" . ?↶)
	      ("ljump_dt" . ?↶)
	      ("ljump_dts" . ?↶)
	      ("ljump_p" . ?↶)
	      ("ljump_e" . ?↶)
	      ("rjump_n" . ?↶)
	      ("rjump_v" . ?↶)
	      ("rjump_t" . ?↷)
	      ("rjump_d" . ?↷)
	      ("rjump_p" . ?↷)
	      ("rjump_e" . ?↷)
	      ("notin_t" . ?∉)
	      ("notin_d" . ?∉)
	      ("notin_p" . ?∉)
	      ("notin_e" . ?∉)
	      ("ni" . ?∋)
	      ("cont" . ?∈)
	      ("<;" . ?≤)
	      ("<;;" . ?≤)
	      ("<;;;" . ?≤)
              ("arr". ?→)
	      ("sup" . ?≥)
	      ("ext" . ?≤)
	      ("supe" . ?≥)
	      ("exte" . ?≤)
	      ("fn" . ?λ)
	      ("off" . ?:)
	      ("in_exp" . ?.)
	      ("oft" . ?:)
	      ("assgn" . ?=)
	      ("/t" . ?/)
	      ("/d" . ?/)
	      ("/ds" . ?/)
	      ("/dt" . ?/)
	      ("/dts" . ?/)
	      ("/p" . ?/)
	      ("/e" . ?/)
	      ("/v" . ?/)
	      ("cast" . ?⊴)
	      ("d_nil" . ?∅)
	      ("dt_nil" . ?∅)))))
